import { TransactionMethod } from "Services/Hydra/order/types";
import {
    AddressType,
    BankWireInfo,
    CashPaymentInfo,
    EventDetails,
    OrderResult,
    PayPalInfo,
    PaymentMethod,
    ShippingMethodQuoteType
} from "../types/OrderContextTypes";

export const useOrder = jest.fn().mockReturnValue({
    orderResult: null as OrderResult | null,
    setOrderResult: jest.fn(),
    shippingMethodQuotes: [] as ShippingMethodQuoteType[],
    setShippingMethodQuotes: jest.fn(),
    selectedShippingMethod: null as ShippingMethodQuoteType | null,
    setSelectedShippingMethod: jest.fn(),
    selectedPaymentMethod: null as TransactionMethod | null,
    setSelectedPaymentMethod: jest.fn(),
    shipToAddress: null as AddressType | null,
    setShipToAddress: jest.fn(),
    signedTerms: false,
    setSignedTerms: jest.fn(),
    userSignature: null as string | null,
    setUserSignature: jest.fn(),
    taxId: "",
    setTaxId: jest.fn(),
    secondaryTaxId: "",
    setSecondaryTaxId: jest.fn(),
    paymentMethod: null as PaymentMethod | null,
    setPaymentMethod: jest.fn(),
    billingAddress: null as AddressType | null,
    setBillingAddress: jest.fn(),
    signatureDateTimeStamp: null as Date | null,
    setSignatureDateTimeStamp: jest.fn(),
    payPal: null as PayPalInfo | null,
    setPayPal: jest.fn(),
    cashPayment: null as CashPaymentInfo | null,
    setCashPayment: jest.fn(),
    bankWire: null as BankWireInfo | null,
    setBankWire: jest.fn(),
    isShipToOffice: false,
    setIsShipToOffice: jest.fn(),
    isCreditCardPaymentValid: false,
    setIsCreditCardPaymentValid: jest.fn(),
    selectedWillCallAddress: null as string | null,
    setSelectedWillCallAddress: jest.fn(),
    pickUpAddressKey: null as string | null,
    setPickUpAddressKey: jest.fn(),
    tppPayload: null as EventDetails | null,
    setTppPayload: jest.fn(),
    isDigitalOnlyOrder: false,
    feedbackSubmitted: false,
    setFeedbackSubmitted: jest.fn(),
    isEnrollmentCompleted: false,
    setIsEnrollmentCompleted: jest.fn()
});

export default useOrder;
