name: AI Code Review

on:
  pull_request:
    branches: [develop] # ทำงานเมื่อ PR มุ่งเข้าสู่ develop (สามารถลบหรือเปลี่ยนชื่อ branch ได้)
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug Environment
        run: |
          echo "Checking environment variables..."
          if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "OPENAI_API_KEY is set"
          else
            echo "OPENAI_API_KEY is not set"
          fi

      - name: Run PR Review
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: 'Automated code review completed',
              event: 'COMMENT'
            })
