name: AI Code Review

on:
  pull_request:
    branches: [develop] # ทำงานเมื่อ PR มุ่งเข้าสู่ develop (สามารถลบหรือเปลี่ยนชื่อ branch ได้)
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install openai

      - name: Debug Environment
        run: |
          echo "Checking environment variables..."
          if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "OPENAI_API_KEY is set"
          else
            echo "OPENAI_API_KEY is not set"
          fi

      - name: Run OpenAI Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Get the list of changed files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          
          # Create review comment
          REVIEW_COMMENT="## AI Code Review\n\n"
          
          for file in $CHANGED_FILES; do
            if [[ $file == *.js || $file == *.ts || $file == *.jsx || $file == *.tsx ]]; then
              # Get the diff for this file
              DIFF=$(git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- $file)
              
              # Call OpenAI API for code review
              REVIEW=$(node -e "
                const OpenAI = require('openai');
                const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
                
                async function reviewCode() {
                  const response = await openai.chat.completions.create({
                    model: 'gpt-3.5-turbo',
                    messages: [
                      {
                        role: 'system',
                        content: 'You are an expert code reviewer. Review the following code changes and provide feedback on code quality, potential bugs, and improvements.'
                      },
                      {
                        role: 'user',
                        content: \`Please review these code changes in ${file}:\n\n${DIFF}\`
                      }
                    ],
                    max_tokens: 500
                  });
                  console.log(response.choices[0].message.content);
                }
                
                reviewCode();
              ")
              
              REVIEW_COMMENT+="### Review for ${file}\n\n${REVIEW}\n\n"
            fi
          done
          
          # Create PR review
          echo "$REVIEW_COMMENT" > review.md
          
          # Create the review using GitHub API
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d @review.md \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews"
